name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3
      #   with:
      #     version: 8

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
           node-version: 20
           cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
           BASE_PATH: '/${{ github.event.repository.name }}'
        run: |
             npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
 # this should match the `pages` option in your adapter-static options
           path: 'build/'
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        # You may use a newer version of https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Generate your content
        run: echo "Optional placeholder. Put your project's static website generator command here."

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:

          # Optional.
          #
          # Default value "." means the root directory of your project will be published.
          #
          # You can use whatever directory your project uses,
          # for example "wwwroot" (without leading "./").
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically
          # by your static website builder.
          source-directory: build

          # Optional. Default value "gh-pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will REMOVE this branch and replace it with new content.
          # (If you want to keep your old "gh-pages" branch,
          # you should define a different target branch for this GPO action to work with.)
          target-branch: gh-pages
  # deploy:
  #   needs: build_site
  #   runs-on: ubuntu-latest

  #   permissions:
  #     pages: write
  #     id-token: write

  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}

  #   steps:
  #     - name: Deploy
  #       id: deployment
  #       uses: actions/deploy-pages@v4
